FROM httpd:2.4.65-alpine3.22
COPY ./public-html/ /usr/local/apache2/htdocs/ 
COPY ./files/server.crt /usr/local/apache2/conf/
COPY ./files/server.key /usr/local/apache2/conf/
COPY ./files/my-httpd.conf /usr/local/apache2/conf/httpd.conf
